var dw_tianya = require('./fetch-books.js')
//dw_tianya.tianya_get_books("http://bbs.tianya.cn/post-no05-243932-1.shtml", "宋词是一朵莲花.txt")
//dw_tianya.tianya_get_books("http://bbs.tianya.cn/post-no05-398052-1.shtml", "中国历史上拯救汉族的十位英雄.txt")
//dw_tianya.tianya_get_books("http://bbs.tianya.cn/post-no05-120226-1.shtml", "千古名将英雄梦1.txt")
//dw_tianya.tianya_get_books("http://bbs.tianya.cn/post-no05-124492-1.shtml", "说春秋.txt")
//dw_tianya.tianya_get_books("http://bbs.tianya.cn/post-no05-146711-1.shtml", "细说两晋南北朝.txt")
//dw_tianya.tianya_get_books("http://bbs.tianya.cn/post-no05-164292-1.shtml", "唐朝从来不淡定.txt")
dw_tianya.fetch_www_books("http://bbs.tianya.cn/post-no05-146165-1.shtml", "正儿八经说隋唐.txt")
